#ifndef LOCAL_CONTRACT_H
#define LOCAL_CONTRACT_H

#define LOCAL_CONTRACT_START_REQUEST 1
#define LOCAL_CONTRACT_END_REQUEST 2
#define LOCAL_CONTRACT_START_RESPONSE 3
#define LOCAL_CONTRACT_END_RESPONSE 4

#define LOCAL_CONTRACT_REQUEST_STATE 10

#endif